set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(NOT DEFINED CMAKE_C_COMPILER)
	if(DEFINED ENV{CTRN_CLANG_PATH})
		set(CMAKE_C_COMPILER "$ENV{CTRN_CLANG_PATH}/bin/clang")
	else()
		set(CMAKE_C_COMPILER "clang")
	endif()
endif()

if(NOT DEFINED CMAKE_CXX_COMPILER)
	if(DEFINED ENV{CTRN_CLANG_PATH})
		set(CMAKE_CXX_COMPILER "$ENV{CTRN_CLANG_PATH}/bin/clang++")
	else()
		set(CMAKE_CXX_COMPILER "clang++")
	endif()
endif()

# Point Clang to GCC's libstdc++ for C++23 features (std::print, std::format, etc.)
# Also bake in the RPATH so the binary finds the correct libstdc++ at runtime
if(DEFINED ENV{CTRN_GCC_PATH})
	# Discover the versioned GCC internal dir dynamically (avoids hardcoding arch triple and version)
	file(GLOB _gcc_install_dirs LIST_DIRECTORIES true "$ENV{CTRN_GCC_PATH}/lib/gcc/*/*")
	if(_gcc_install_dirs)
		list(GET _gcc_install_dirs 0 _gcc_install_dir)
		add_compile_options("--gcc-install-dir=${_gcc_install_dir}")
		add_link_options("--gcc-install-dir=${_gcc_install_dir}")
		message(STATUS "Clang using GCC install dir: ${_gcc_install_dir}")
	else()
		message(WARNING "CTRN_GCC_PATH is set but no GCC installation found under $ENV{CTRN_GCC_PATH}/lib/gcc/ — C++23 headers may be missing")
	endif()
	set(CMAKE_BUILD_RPATH "$ENV{CTRN_GCC_PATH}/lib64")
	set(CMAKE_INSTALL_RPATH "$ENV{CTRN_GCC_PATH}/lib64")
	message(STATUS "Using GCC libstdc++ from CTRN_GCC_PATH: $ENV{CTRN_GCC_PATH}")
endif()

if(DEFINED ENV{CTRN_CLANG_PATH})
	message(STATUS "Using Clang from CTRN_CLANG_PATH: $ENV{CTRN_CLANG_PATH}")
else()
	message(STATUS "Using system Clang (set CTRN_CLANG_PATH to use custom Clang)")
endif()

message(STATUS "CMAKE_C_COMPILER = ${CMAKE_C_COMPILER}")
message(STATUS "CMAKE_CXX_COMPILER = ${CMAKE_CXX_COMPILER}")
